### ISSUE TITLE
(!) CardList view/design

### ISSUE THREAD

**Issue by jokla17** [wtrwinberg/Kateesa#4]
We should discuss how the list of cards behaves. At present, the wireframes dictate that a list of cards has to be present in both **_EditCardView_** and **_CreateCardView_**. We discussed this in the developer-team, and came to the conclusion that this design feature has some flaws, in that it seems unintuitive to have lists that are identical, but are used for different purposes in different views. 

Our suggestion is:
- Have a scrollable list of cards-in-current-deck in the **_EditDeckView_**. 
  - If the user taps one of the cards in this list, they are sent to the **_EditCardView_**. After editing and confirming their changes, they are sent back to the **_EditDeckView_**. 
- The "+" button in the Bottom Toolbar of **_EditDeckView_** would behave normally
- The **_CreateCardView_** no longer has the cardList, but instead has a pop-up message displaying "Added Card to (deckName)" when a user clicks the "addCard"-button.
  - When the user is done adding cards, they can press "save" or something similar, which again sends them back to the **_EditDeckView_**, or something of that nature.

We would like some feedback from the design team on this issue, our proposal for a solution and whether or not you would be willing to make these changes in your views - if we decide to fix this 👍

**Comment by EmmaBovtrup** [comment]
Hey guys! We have dicussed this a bit in our evening meeting and we came to the conclusion that we didnt really see it as unintuitive and we thought it would logical to have a scrollable list of the current cards in the deck available in the create-card view. In that way the user can see if they are adding a duplicate question or if they want a follow up question to an earlier question. We also compared it to the application Quizlet and they have it the same way as us :) Hope it is okay with you guys, otherwise we can have a discussion together physical instead of doing it here :)
